from pathlib import Path

import yaml

from footy.live.name_map import map_team, map_stage

GENERATED_HEADER = "# GENERATED by footy.live.ingest — do not edit manually\n"


def _group_letter(raw_group: str) -> str:
    return raw_group.split("_")[-1]


def build_played_matches(provider_matches, name_map, known_teams, stage_map) -> list:
    out = []
    for pm in provider_matches:
        if pm.home_score is None or pm.away_score is None:
            raise ValueError(f"match {pm.api_match_id} has no final score")
        team_a = map_team(pm.home_team, name_map, known_teams)
        team_b = map_team(pm.away_team, name_map, known_teams)
        stage = map_stage(pm.stage, stage_map)
        group = None
        if stage == "group":
            if pm.group is None:
                raise ValueError(f"group-stage match {pm.api_match_id} has no group")
            group = _group_letter(pm.group)
        out.append({"match_id": pm.api_match_id, "stage": stage, "group": group,
                    "team_a": team_a, "team_b": team_b,
                    "goals_a": pm.home_score, "goals_b": pm.away_score})
    return out


def ingest(provider, structure, name_map, stage_map, out_path) -> int:
    known_teams = {t for group in structure.groups.values() for t in group}
    played = build_played_matches(provider.fetch_finished(), name_map, known_teams, stage_map)
    dedup = {}
    for m in played:
        dedup[m["match_id"]] = m
    final = sorted(dedup.values(), key=lambda m: (m["stage"], m.get("group") or "", m["match_id"]))
    body = yaml.safe_dump({"played_matches": final}, sort_keys=False, allow_unicode=True)
    Path(out_path).write_text(GENERATED_HEADER + body, encoding="utf-8")
    return len(final)
