teams:
  "USA": "United States"
  "Korea Republic": "South Korea"
  "IR Iran": "Iran"
  "Côte d'Ivoire": "Ivory Coast"
  "Czechia": "Czech Republic"
  "Bosnia-Herzegovina": "Bosnia and Herzegovina"
  "Cabo Verde": "Cape Verde"
  "Cape Verde Islands": "Cape Verde"
  "Türkiye": "Turkey"
  "Congo DR": "DR Congo"
